# Use an official NGINX image as the base image
FROM nginx:1.24.0-alpine-slim

# Copy the Nginx configuration file
COPY ./laravel.conf /etc/nginx/conf.d/default.conf

# Copy the entrypoint script
COPY ./entrypoint.sh /usr/local/bin/entrypoint.sh

# Make the entrypoint script executable
RUN chmod +x /usr/local/bin/entrypoint.sh

# Set the entrypoint to use the custom script
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

