version: '3'
services:
    #PHP Service
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=$(APP_ENV)
        environment:
            - APP_ENV=$(APP_ENV)
            - CONTAINER_ROLE=app
            - DB_HOST=database
            - DB_PORT=3306

        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - database
    #database server

    database:
        image: mysql:8.0
        ports:
            - "3307:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql

    node:
        build:
            context: .
            target: node
        volumes:
            - ./:/urs/src
            - ./node_modules:/usr/src/node_modules
        tty: true
volumes:
    db_data: ~
