# Use an official NGINX image as the base image
FROM nginx:1.24.0-alpine-slim
ARG PORT
# Copy the NGINX configuration file
COPY ./laravel.conf /etc/nginx/conf.d/default.conf






# Expose port 80 (this is just for reference, Render will handle the actual port binding)
EXPOSE 80

#demon off
CMD ["nginx", "-g", "daemon off;"]
