version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile.php-fpm
        container_name: php-fpm
        env_file:
            - .env.production
        volumes:
            - ./public:/var/www/html/public
        networks:
            - rentalProject-api-network

    web-server:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        container_name: web-server
        ports:
            - "${PORT:-8080}:8080"
        volumes:
            - ./public:/var/www/html/public
        networks:
            - rentalProject-api-network

    mysql:
        image: mysql:latest
        container_name: mysql_container
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: rentalProject
            MYSQL_USER: rentalProject
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
            - ./dumps:/docker-entrypoint-initdb.d
        networks:
            - rentalProject-api-network

volumes:
    mysql_data:


networks:
    rentalProject-api-network:
