version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile.php-fpm # The Dockerfile containing the PHP-FPM setup
        container_name: php-fpm
        env_file:
            - .env.production
        volumes:
            - ./public:/var/www/html/public
        networks:
            - rentalProject-api-network
        deploy:
            resources:
                limits:
                    cpus: "0.5"  # Use 50% of 1 CPU (half CPU)
        restart: unless-stopped

    web-server:
        build:
            context: .
            dockerfile: Dockerfile.nginx # The Dockerfile containing the NGINX setup
        container_name: web-server
        volumes:
            - ./public:/var/www/html/public
        networks:
            - rentalProject-api-network
        ports:
            - "80:80"
        deploy:
            resources:
                limits:
                    cpus: "0.25"  # Use 25% of 1 CPU (quarter CPU)
        restart: unless-stopped

    mysql:
        image: mysql:latest
        container_name: mysql_container
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: rentalProject
            MYSQL_USER: rentalProject
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
            - ./dumps:/docker-entrypoint-initdb.d
        ports:
        - "3306:3306"  
        command: --log-error-verbosity=3  # Increase logging verbosity
        networks:
            - rentalProject-api-network
        deploy:
            resources:
                limits:
                    cpus: "0.25"  # Use 25% of 1 CPU (quarter CPU)
        restart: unless-stopped

volumes:
    mysql_data:

networks:
    rentalProject-api-network:
